from supabase import create_client
import os
SUPABASE_URL="https://ywybifmunuyuwqhbbmba.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eWJpZm11bnV5dXdxaGJibWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzA3MzUsImV4cCI6MjA3Mzc0NjczNX0.jo0QhOw_7T_QuScwJDjKBktRoYb7VslH5urC08NZ0D8"


supabase= create_client(SUPABASE_URL, SUPABASE_KEY)
